<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ValheimDir Condition="'$(ValheimDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimDir>
    <ValheimManagedDir Condition="'$(ValheimManagedDir)' == ''">$(ValheimDir)\valheim_Data\Managed</ValheimManagedDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="assembly_valheim"><HintPath>$(ValheimManagedDir)\assembly_valheim.dll</HintPath></Reference>
    <Reference Include="Mono.Cecil"><HintPath>$(ValheimDir)\BepInEx\core\Mono.Cecil.dll</HintPath></Reference>
    <Reference Include="kg.ValheimEnchantmentSystem"><HintPath>..\..\bin\Debug\kg.ValheimEnchantmentSystem.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>..\..\Libs\0Harmony.dll</HintPath></Reference>
    <Reference Include="MonoMod.Utils"><HintPath>$(ValheimDir)\BepInEx\core\MonoMod.Utils.dll</HintPath></Reference>
    <None Include="$(ValheimManagedDir)\*.dll" Exclude="$(ValheimManagedDir)\mscorlib.dll;$(ValheimManagedDir)\netstandard.dll;$(ValheimManagedDir)\System*.dll" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\Libs\BepInEx.dll" Link="BepInEx.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
